[package]
name = "example_ws_stream_csv"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
foxglove = { path = "../../foxglove" }
