[package]
name = "example_ws_playback_control"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
env_logger = "0.11"
foxglove = { path = "../../foxglove" }
tokio = { version = "1.47", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
