[package]
name = "example_prost"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove", default-features = false }
prost = "0.14"

[build-dependencies]
prost-build = "0.14"
