[package]
name = "remote_access_tests"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
foxglove = { path = "../foxglove", features = ["remote_access", "_protocol"] }
livekit = { version = "0.7.29", features = ["rustls-tls-native-roots"] }
livekit-api = { version = "0.4", default-features = false, features = ["access-token"] }
axum = "0.8"
reqwest = { version = "0.13", features = ["json"] }
tokio.workspace = true
serde.workspace = true
serde_json = "1.0"
anyhow = "1"
tracing.workspace = true
futures-util = "0.3"
dotenvy = "0.15"

[dev-dependencies]
tracing-test.workspace = true

[lints]
workspace = true
