[package]
name = "example_ws_ranged_playback"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
ctrlc = "3.4"
env_logger = "0.11"
foxglove = { path = "../../foxglove" }
tracing = { version = "0.1", features = ["log"] }
